apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_USER: student_var31
  POSTGRES_PASSWORD: P@$$w0rd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: "osrm"
  DB_HOST: "db-service"
  DB_PORT: "5432"